[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/iclock/cdata"
  to = "/.netlify/functions/cdata"
  status = 200
  force = true

[[redirects]]
  from = "/iclock/getrequest"
  to = "/.netlify/functions/cdata"
  status = 200
  force = true
